Post.create([
  { title: "3 Digital Nomads Living a Life Less Ordinary",
    author: "Brennan Gamwell",
    date_published: "2014",
    URL: "https://www.upwork.com/blog/2014/07/3-digital-nomads-living-life-less-ordinary/",
    synopsis: "Digital Nomads are people who have ditched their desk to pursue a life less ordinary, taking work with them while on the go. Digital Nomads don’t always plan their lifestyle, however — sometimes they see an opportunity and just take the leap.",
    image: "",
    source: "Upwork Blog"
  },
  { title: "How to be a Digital Nomad When You Have a Family",
    author: "Brennan Gamwell",
    date_published: "2014",
    URL: "https://www.upwork.com/blog/2014/06/digital-nomad-family/",
    synopsis: "Liisa, her husband, and her two sons (ages six and eight) live part of every year as Digital Nomads in Tamarindo, Costa Rica — a scenic coastal town on the Pacific Ocean. They can walk across the street to visit the beach and swim in the warm Pacific water whenever they want, or watch the sun set beneath the waves from their front window.",
    image: "",
    source: "Upwork Blog"
  },
  { title: "Digital Nomad Olivia: How to Start Your Journey",
    author: "Brennan Gamwell",
    date_published: "2014",
    URL: "https://www.upwork.com/blog/2014/05/digital-nomad-olivia-tips-to-start-your-journey/",
    synopsis: "Olivia Amter’s journey as a Digital Nomad started back in 2007 when she was a newly minted high school graduate. At the time, she was unsure about practically everything: what to study in college, what career she would choose, where she would live. Her mother suggested she take a “gap year” before college to leave her home in Washington, D.C., to explore, grow, and reflect.",
    image: "",
    source: "Upwork Blog"
  },
  { title: "Radhika: A Traveling Foodie",
    author: "Brennan Gamwell",
    date_published: "2014",
    URL: "https://www.upwork.com/blog/2014/04/radhika-traveling-foodie/",
    synopsis: "Radhika has always had the “travel bug”—she’s wanted to see the world for as long as she can remember. But for many, including herself, traveling can be difficult.",
    image: "",
    source: "Upwork Blog"
  },
  { title: "Jay: Ex Million-Mile Commuter Turned Digital Nomad",
    author: "Brennan Gamwell",
    date_published: "2014",
    URL: "https://www.upwork.com/blog/2014/02/meet-jay-shapiro-digital-nomad/",
    synopsis: "For most of us, commuting is a time-consuming nuisance. But for some, commuting to the office can be downright brutal.",
    image: "",
    source: "Upwork Blog"
  },
  { title: "Digital Nomad Winner: Quit, Sold and Hit the Road",
    author: "Brennan Gamwell",
    date_published: "2014",
    URL: "https://www.upwork.com/blog/2014/04/digital-nomad-winner-quit-sold-hit-road/",
    synopsis: "Glenn Dixon and his wife, Dixie, are enjoying their latest location as Digital Nomads: San Cristobal de las Casas, a picturesque city nestled in the forested mountains of southern Mexico.",
    image: "",
    source: "Upwork Blog"
  },
  { title: "The 6-Step Process Behind a Winning Content Strategy",
    author: "Brennan Gamwell",
    date_published: "2015",
    URL: "http://www.contentfaq.com/the-6-step-process-behind-a-winning-content-strategy/",
    synopsis: "Process is an integral part of content strategy. Without it, you’re missing out on research and the thought process that accompanies creating impactful, intentional content.",
    image: "",
    source: "ContentFAQ"
  },
  { title: "25 Resources for Writing Irresistible Web Headlines",
    author: "Brennan Gamwell",
    date_published: "2015",
    URL: "http://www.contentfaq.com/25-resources-writing-irresistible-web-headlines/",
    synopsis: "Blogging is a big part of an effective content strategy, but how do you get people to click on your content? But there’s one, small component that can mean the difference between 7,000 clicks and 750,000: Writing effective headlines.",
    image: "",
    source: "ContentFAQ"
  },
  { title: "9 Tactics To Get More Clicks On Your Blog",
    author: "Brennan Gamwell",
    date_published: "2015",
    URL: "http://www.contentfaq.com/9-tactics-get-clicks-blog/",
    synopsis: "So you’ve launched a blog, written some great content, and done your keyword homework – now what? Let’s face it: building a blog is the easy part. But, If you write it, readers won’t necessarily come. That’s probably why so many of our clients and readers ask right away how they can attract and engage readers to their blog.",
    image: "",
    source: "ContentFAQ"
  },
  { title: "How Content Marketing Will Make You Money",
    author: "Brennan Gamwell",
    date_published: "2015",
    URL: "http://www.contentfaq.com/content-marketing-will-make-money/",
    synopsis: "Content marketing is all about producing content that attracts users to your website: Blog posts, images, website text, email marketing campaigns. When users find value in your content—when they find it funny, educational or entertaining—they’ll keep coming back to your website. They’ll want more.",
    image: "",
    source: "ContentFAQ"
  },
  { title: "Keyword Research for Blog Posts: A Quick & Dirty Guide",
    author: "Brennan Gamwell",
    date_published: "2015",
    URL: "http://www.contentfaq.com/keyword-research-for-blog-posts-a-quick-dirty-guide/",
    synopsis: "Keyword research tells us exactly what people are searching for in Google and exactly what words will draw readers to our posts. Knowing what topics people are searching for will help your writing become tighter, clearer and more relevant to your audience.",
    image: "",
    source: "ContentFAQ"
  },
  { title: "Don’t Forget Me! Ensuring Distributed Team Members Aren’t Left Out",
    author: "Brennan Gamwell",
    date_published: "2014",
    URL: "https://www.linkedin.com/pulse/20140311131554-758147-don-t-forget-me-ensuring-distributed-team-members-aren-t-left-out?trk=mp-reader-card",
    synopsis: "Originally published as a ghostwritten piece for oDesk CEO Gary Swart.",
    image: "",
    source: "LinkedIn"
  },
  { title: "The Art of Feedback: 5 Tactics that Work",
    author: "Brennan Gamwell",
    date_published: "2014",
    URL: "https://www.linkedin.com/pulse/20140211143643-758147-the-art-of-feedback-5-tactics-that-work?trk=mp-reader-card",
    synopsis: "Originally published as a ghostwritten piece for oDesk CEO Gary Swart.",
    image: "",
    source: "LinkedIn"
  },
  { title: "Digital Nomads: A Work Freedom Revolution",
    author: "Brennan Gamwell",
    date_published: "2014",
    URL: "https://www.linkedin.com/pulse/20140204142733-758147-digital-nomads-a-work-freedom-revolution-video?trk=mp-reader-card",
    synopsis: "Originally published as a ghostwritten piece for oDesk CEO Gary Swart.",
    image: "",
    source: "LinkedIn"
  },
  { title: "The 'On-the-Spot' Performance Review",
    author: "Brennan Gamwell",
    date_published: "2014",
    URL: "https://www.linkedin.com/pulse/20140130142744-758147-the-on-the-spot-performance-review?trk=mp-reader-card",
    synopsis: "Originally published as a ghostwritten piece for oDesk CEO Gary Swart.",
    image: "",
    source: "LinkedIn"
  },
  { title: "Inspiring Freelancers: 5 Pros Who Made Goals, Took Risks & Came Out On Top",
    author: "Brennan Gamwell",
    date_published: "2014",
    URL: "https://www.linkedin.com/pulse/20140114140357-758147-inspiring-freelancers-5-pros-who-made-goals-took-risks-came-out-on-top?trk=mp-reader-card",
    synopsis: "Originally published as a ghostwritten piece for oDesk CEO Gary Swart.",
    image: "",
    source: "LinkedIn"
  },
  { title: "1 Million Man Hours, No Injuries",
    author: "Brennan Gamwell",
    date_published: "2013",
    URL: "http://www.ironworkers.org/news-magazine/ironworker-magazine/archives/articles/2013/05/07/1-000-000-man-hours-no-injuries",
    synopsis: "Have you ever wondered how construction workers stay safe on the job? This feature explores worksite safety at powerplant in California.",
    image: "",
    source: "Ironworkers.org"
  }
  ]);
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')